"""Update book_db

Revision ID: 0905d3118c8f
Revises: 296c4a1254c2
Create Date: 2021-11-26 19:57:01.532994

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0905d3118c8f'
down_revision = '296c4a1254c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    op.drop_column('book', 'rating')
    op.drop_column('book', 'stock')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('stock', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('book', sa.Column('rating', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_table('books',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('book_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('publisher', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('author', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('publication_date', mysql.DATETIME(), nullable=True),
    sa.Column('pages', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('isbn', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('link', mysql.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
