"""delete favorite_color

Revision ID: 296c4a1254c2
Revises: 53b8f9010d77
Create Date: 2021-11-26 09:03:34.878831

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '296c4a1254c2'
down_revision = '53b8f9010d77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_color', mysql.VARCHAR(length=30), nullable=True))
    # ### end Alembic commands ###
